import "./scripts/header-observers.js";
import "./scripts/header-top-height.js";
import "./scripts/catalog-button.js";
import "./scripts/catalog-block.js";
import "./scripts/search-block.js";
import "./scripts/burger.js";
import "./scripts/burger-header.js";
import "./scripts/dropdown-button.js";
import "./scripts/spoilers.js";
